[package]
name = "py03"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# pyo3 = "*"
pyo3 = { version = "0.14.1", features = ["extension-module"] }# inline_python = "*" 
